my_string = input('Произвольный текст: ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(my_string.replace('Жаркое лето', 'Ж'))
print(my_string.replace('Жаркое лето', 'о'))